version: "3"

# Environment variables
# ----------------------
# POSTGRES_USER: The username of the default user
# POSTGRES_PASSWORD: The password of the default user
# POSTGRES_DATA: The path to the data directory (bind)
#
# PGADMIN_EMAIL: The email address of the default user
# PGADMIN_PASSWORD: The password of the default user
# PGADMIN_DATA: The path to the data directory (bind)

services:
  db:
    image: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ${POSTGRES_DATA}:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    ports:
      - "32768:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    volumes:
      - ${PGADMIN_DATA}:/var/lib/pgadmin
