# This is a docker-compose file for running Sonarr, Radarr and Jellyfin
# It is based on the linuxserver.io images

# ENVIRONMENT VARIABLES
# SONNAR_BIND: The folder where Sonarr will store its data
# RADARR_BIND: The folder where Radarr will store its data
# JELLYFIN_BIND: The folder where Jellyfin will store its data
#
# MOVIES_BIND: The folder where your movies are stored
# TV_BIND: The folder where your TV shows are stored

version: '3.7'

services:
  jellyfin:
    image: linuxserver/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ${JELLYFIN_BIND}:/config
      - ${MOVIES_BIND}:/media/movies
      - ${TV_BIND}:/media/tv
    ports:
      - 8096:8096
    networks:
      - jellyfin

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ${RADARR_BIND}:/config
      - ${MOVIES_BIND}:/movies
      - ${TV_BIND}:/tv
    ports:
      - 7878:7878
    networks:
      - jellyfin

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ${SONARR_BIND}:/config
      - ${MOVIES_BIND}:/movies
      - ${TV_BIND}:/tv
    ports:
      - 8989:8989
    networks:
      - jellyfin

networks:
  jellyfin:
    driver: bridge
