FROM bellsoft/liberica-openjdk-alpine:18

RUN mkdir /magma
RUN mkdir /magma-bin

EXPOSE 25565
EXPOSE 25575

WORKDIR /magma-bin
RUN wget https://git.magmafoundation.org/api/v4/projects/5/packages/maven/org/magmafoundation/Magma/1.18.2-40.2.1-606f9b2c/Magma-1.18.2-40.2.1-606f9b2c-server.jar -O Magma.jar

WORKDIR /magma
CMD java -server -Duser.dir=/magma -Xms${MC_RAM} -Xmx${MC_RAM} -jar /magma-bin/Magma.jar nogui